#!/bin/bash


#This script performs pseudoalignment quantification with Kallisto
#Uses Kallisto which can be installed with conda <conda -install kallisto>
## https://pachterlab.github.io/kallisto/
## useful tutorial on kallisto @ https://github.com/griffithlab/rnaseq_tutorial/wiki/Kallisto

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
#This script assumes your trimmed, demultiplexed input files are in subdirectry of the project folder, results/trimmed

#make directory for kallisto results

mkdir -p Results/kallisto/chronic.stress.roots

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
#run kallisto
 
#####
#if you haven't made an index uncomment the following script
#######

#kallisto index --index=Results/kallisto_analysis/Suipun1_GeneCatalog_transcripts_kallisto_index Results/kallisto_analysis/Suipun1_GeneCatalog_Transcripts/Suipun1_GeneCatalog_transcripts_20200424.nt.fasta.gz

# command for aligning paired-end reads
kallisto quant -i inputFastaName.index -o sample1_kallisto -b 100 sample1_read1.fastq.gz sample1_read2.fastq.gz

#for loop# 

for FWD in $( find Results/paired_fastq -name "*R1_001_trimmed_paired.fastq.gz")
do 
REV=`echo $FWD | sed 's/R1_001_trimmed_paired.fastq.gz/R2_001_trimmed_paired.fastq.gz/'`
name=$(basename ${FWD} | sed 's/.R1_001_trimmed_paired.fastq.gz//')
kallisto quant --index=Results/kallisto_analysis/Suipun1_GeneCatalog_transcripts_kallisto_index --output-dir=Results/kallisto_analysis/chronic.stress.roots/${name} -b 100 --threads=4 $FWD $REV
done
